name       : torbrowser-launcher
version    : 0.3.1
release    : 1
source     :
    - https://github.com/micahflee/torbrowser-launcher/archive/v0.3.1.tar.gz : b08b5a09f579fc00ccfac3c4ba9a92d7b2c9d4e2bb8bd3444bfc96a9892a113d
license    : BSD-1-Clause
component  : network.web.browser
summary    : Securely and easily install Tor Browser
description: |
    Tor Browser Launcher is intended to make Tor Browser easier to install and use for GNU/Linux users.
rundeps    :
    - gnupg
    - python3-qt5
    - python-gpg
    - python-pysocks
    - python-requests
    - tor
setup      : |
    %python3_setup
install    : |
    %python3_install
