name       : torbrowser-launcher
version    : 0.3.6
release    : 13
source     :
    - https://github.com/micahflee/torbrowser-launcher/archive/refs/tags/v0.3.6.tar.gz : 9de3207d940b0043346e4ccfa468ffa89c61bcce8239ba3ac854506b81967b09
license    : BSD-1-Clause
component  : network.web.browser
summary    : Securely and easily install Tor Browser
description: |
    Tor Browser Launcher is intended to make Tor Browser easier to install and use for GNU/Linux users.
builddeps  :
    - python-distro
rundeps    :
    - gnupg
    - python3-qt5
    - python-gpg
    - python-pysocks
    - python-requests
    - tor
setup      : |
    %patch -p1 < $pkgfiles/Return-early-if-tbb-path-doesnt-exist.patch
    %python3_setup
install    : |
    %python3_install
