name       : torbrowser-launcher
version    : 0.3.2
release    : 5
source     :
    - https://github.com/micahflee/torbrowser-launcher/archive/v0.3.2.tar.gz : 25ad4b0c70579628bf18f4cdcd18ac303fe4f7f1c590cc48df2a87651c92991c
    - http://lists.torproject.org/pipermail/tbb-dev/attachments/20200722/82030b51/attachment-0001.key : 81ad7ce6b6808bfc4d15460c2cc1bbd80ddf3043dfef4d6179ac85d7b4141210
license    : BSD-1-Clause
component  : network.web.browser
summary    : Securely and easily install Tor Browser
description: |
    Tor Browser Launcher is intended to make Tor Browser easier to install and use for GNU/Linux users.
rundeps    :
    - gnupg
    - python3-qt5
    - python-gpg
    - python-pysocks
    - python-requests
    - tor
setup      : |
    %apply_patches
    # Import updated signing key
    cp $sources/attachment-0001.key $workdir/share/torbrowser-launcher/tor-browser-developers.asc
    %python3_setup
install    : |
    %python3_install
